<?php

/**
 * @package   yii2-widget-flatpickr
 * @author    Ishengge <ishengge@gmail.com>
 * @version   1.0.0
 */

namespace lintion\flatpickr;;

use lintion\flatpickr\FlatpickrAsset;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\widgets\InputWidget;
use yii\helpers\Html;

class Flatpickr extends InputWidget
{
    public $id;

    /**
     * @var array flatpickr config options.
     */
    public $clientConfigs = [];

    /**
     * @var string flatpickr theme name, To use a theme of your choice, Specific @see <https://chmln.github.io/flatpickr/themes/ no set is default>
     */
    public $theme;

    public $defaultConfigs = [
        'locale' => 'zh',
        'enableTime' => true,
        'wrap' => true,
    ];

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->registerClientScript();
        echo $this->Html();
    }

    private function registerClientScript()
    {
        $this->id = $this->options['id'].'-lintion';
        $config = Json::encode(ArrayHelper::merge($this->defaultConfigs, $this->clientConfigs));
        $js =<<<JS
flatpickr("#{$this->id}", $config);
JS;

        $view = $this->getView();
        FlatpickrAsset::register($view);
        $view->registerJs($js);
    }

    /**
     * @return string
     */

    private function Html()
    {
        $options = ArrayHelper::merge(["class" => "form-control", 'data-input' => true], $this->options);
        if ($this->hasModel()){
            $input = Html::activeTextInput($this->model, $this->attribute, $options);
        }else{
            $input = Html::textInput($this->name, $this->value, $options);
        }

        $html =<<<HTML
<div id="{$this->id}" class="input-group">

{$input}
   
    <span class="input-group-btn" title="clear" data-clear>
       <button type="button" class="btn btn-danger">清除</button>
    </span>
    
</div>
HTML;

        return $html;

    }
}